# notifies users from CODENOTIFY files if a PR changed any files
# that they subscribe to
name: codenotify

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  codenotify:
    runs-on: ubuntu-latest
    name: codenotify
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: sourcegraph/codenotify@v0.6.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
